spring:
  data:
    mongodb:
      authentication-database: admin
      database: social-network
      host: localhost
      port: 27017
      
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
